[package]
name = "dnd-simp"
version = "0.1.0"
edition = "2021"

[dependencies]
anyhow = "1.0.94"
rand = "0.8.5"
regex = "1.11.1"
serde = { version = "1.0.216", features = ["derive"] }
serde_json = "1.0.133"
serde_yaml = "0.9.34"
